// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjPHKfuyTOAHOaumNj-kiLhfgmenxx6x0',
    appId: '1:360554408022:web:157baa544ed022f93a33f7',
    messagingSenderId: '360554408022',
    projectId: 'ecommerceapp-fa22e',
    authDomain: 'ecommerceapp-fa22e.firebaseapp.com',
    storageBucket: 'ecommerceapp-fa22e.appspot.com',
    measurementId: 'G-35FHHFQJMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnY6nNWnd8FNbbrjhD2WLnDzYEXi9qjIA',
    appId: '1:360554408022:android:90681f56fd155c223a33f7',
    messagingSenderId: '360554408022',
    projectId: 'ecommerceapp-fa22e',
    storageBucket: 'ecommerceapp-fa22e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9Lumt_AGKDpHctK5Ww65v3Lo8YBAUtk',
    appId: '1:360554408022:ios:d5bc0a6ae93219d73a33f7',
    messagingSenderId: '360554408022',
    projectId: 'ecommerceapp-fa22e',
    storageBucket: 'ecommerceapp-fa22e.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO9Lumt_AGKDpHctK5Ww65v3Lo8YBAUtk',
    appId: '1:360554408022:ios:d5bc0a6ae93219d73a33f7',
    messagingSenderId: '360554408022',
    projectId: 'ecommerceapp-fa22e',
    storageBucket: 'ecommerceapp-fa22e.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjPHKfuyTOAHOaumNj-kiLhfgmenxx6x0',
    appId: '1:360554408022:web:e2788562f792ebb83a33f7',
    messagingSenderId: '360554408022',
    projectId: 'ecommerceapp-fa22e',
    authDomain: 'ecommerceapp-fa22e.firebaseapp.com',
    storageBucket: 'ecommerceapp-fa22e.appspot.com',
    measurementId: 'G-XZ27HRB9XG',
  );
}
